export const SITE_TITLE = 'Clarity'
export const SITE_DESCRIPTION = 'Free up your time with pre-built classes that update site-wide automatically. Focus on building, not fixing.'
export const SITE_URL = 'https://clarity.dev'
export const SITE_IMAGE = '/og.png'
export const SITE_EMAIL = 'hello@clarity.dev'
export const SITE_BLOG = 'https://dev.to/clarity/'
export const SITE_STORE = 'https://clarity.lemonsqueezy.com/'
export const SITE_SOCIAL_TWITTER = 'https://twitter.com/clarity_ui'
export const SITE_SOCIAL_FACEBOOK = 'https://web.facebook.com/clarityui'
export const SITE_SOCIAL_GITHUB = 'https://github.com/clarity-ui/html.clarity.io'
export const SITE_SOCIAL_LINKEDIN = 'https://www.linkedin.com/company/95954582'
export const SITE_SOCIAL_YOUTUBE = 'https://www.youtube.com/@clarity-ui'
export const SITE_SOCIAL_THREADS = 'https://www.threads.net/@clarity_ui'

export const MESCHAC_AVATAR = 'https://avatars.githubusercontent.com/u/47919550?v=4'
export const BERNARD_AVATAR = 'https://avatars.githubusercontent.com/u/31113941?v=4'
export const THEO_AVATAR = 'https://avatars.githubusercontent.com/u/68236786?v=4'
export const GLODIE_AVATAR = 'https://avatars.githubusercontent.com/u/99137927?v=4'
